### ISSUE TITLE
Make this packageable for distros

### ISSUE THREAD

**Issue by trusktr** [seenaburns/dex-ui#1]
make this packageable for distros. Arch Linux, but Ubuntu would be fine, then it can be adapted for Arch. :D

**Comment by r0nk** [comment]
He said before that porting it to different architectures would be more of the open source communities job, as this wasn't originally supposed to be an open source project, so It would be a good idea if someone could make a fork for this.

**Comment by trusktr** [comment]
For sure. Is there a video of this?

**Comment by anthonyclays** [comment]
AFAIK there's only the small [video](https://gfycat.com/CourageousWiltedKrill) that was posted to [/r/unixporn](https://reddit.com/r/unixporn).

**Comment by trusktr** [comment]
niice!

**Comment by seenaburns** [comment]
As @r0nk said, this is not something I plan on doing, but I've added some explanation to the README on how to make it run.
